# Default values for keyVaultCsiIntegration.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


identitybinding:
  clientid: sampleClientId
  resourceid: sampleresourceId
  azureidentity: sampleAzureIdentity

secretprovider:
  name: azure-kv
  keyvaultname: sampleKeyvaultName
  tenantid: sampleTenantId
  secretname: sampleSecretName